"""initial schema

Revision ID: 7fc1fa8a1239
Revises: 
Create Date: 2026-06-12 20:49:29.083190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc1fa8a1239'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('reminder_hour', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('score_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_user_type_created', 'events', ['user_id', 'type', 'created_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('brief_md', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase_id', 'slug')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase_id', 'slug')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('prompt_md', sa.Text(), nullable=False),
    sa.Column('submission_md', sa.Text(), nullable=True),
    sa.Column('feedback_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=16), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('progress_idx', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id')
    )
    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question_json', sa.JSON(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_topic_id'), 'question_bank', ['topic_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('questions_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('ladder_index', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('last_result', sa.String(length=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id')
    )
    op.create_index('ix_review_items_user_due', 'review_items', ['user_id', 'due_date'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answers_json', sa.JSON(), nullable=False),
    sa.Column('score_pct', sa.Float(), nullable=True),
    sa.Column('weak_tags_json', sa.JSON(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_attempts_user_finished', 'quiz_attempts', ['user_id', 'finished_at'], unique=False)
    op.create_table('user_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_phase_id', sa.Integer(), nullable=True),
    sa.Column('current_topic_id', sa.Integer(), nullable=True),
    sa.Column('active_lesson_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['active_lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['current_phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['current_topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_state')
    op.drop_index('ix_quiz_attempts_user_finished', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index('ix_review_items_user_due', table_name='review_items')
    op.drop_table('review_items')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_question_bank_topic_id'), table_name='question_bank')
    op.drop_table('question_bank')
    op.drop_table('project_progress')
    op.drop_table('lessons')
    op.drop_table('exercises')
    op.drop_table('topics')
    op.drop_table('projects')
    op.drop_index('ix_events_user_type_created', table_name='events')
    op.drop_table('events')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('phases')
    # ### end Alembic commands ###
